apiVersion: v1
kind: Namespace
metadata:
  name: demo-ns-hello-world
---  
kind: Service
apiVersion: v1
metadata:
  name: demo-svc-hello-world
  namespace: demo-ns-hello-world
spec:
  selector:
    app: demo-app-hello-world
  ports:                                                                                                                                                                                                                                                              
  - protocol: TCP
    port: 80
    nodePort: 30001
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy-hello-world
  namespace: demo-ns-hello-world
  labels:
    app: backend
    platform: java
spec:
  selector:
      matchLabels:
        app: demo-app-hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-app-hello-world
    spec:
      containers:
        - name: demo-container-hello-world
          image: g33kzone/sb-hello-world:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
          livenessProbe:
              httpGet:
                port: 8080
                path: /actuator/liveness
              initialDelaySeconds: 30
              periodSeconds: 20
              timeoutSeconds: 2
              failureThreshold: 1
              successThreshold: 1
