kind: Service
apiVersion: v1
metadata:
  name: demo-svc-hello-world
spec:
  selector:
    app: demo-app-hello-world
  ports:                                                                                                                                                                                                                                                              
  - protocol: TCP
    port: 80
    nodePort: 30001
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy-hello-world
  # namespace: sb-devops-demo
  labels:
    app: backend
    platform: java
spec:
  selector:
      matchLabels:
        app: demo-app-hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-app-hello-world
    spec:
      containers:
        - name: demo-container-hello-world
          image: g33kzone/sb-hello-world:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
